file <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, stringsAsFactors = FALSE)
new_file <- file[which(file$Date == '1/2/2007' | file$Date == '2/2/2007'), ]
new_file['DateTime'] <- paste(new_file$Date, new_file$Time, sep = " ")
new_file$DateTime <- strptime(new_file$DateTime, format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(new_file$DateTime, new_file$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(new_file$DateTime, new_file$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(new_file$DateTime, new_file$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(new_file$DateTime, new_file$Sub_metering_2, type = "l", col = "red")
points(new_file$DateTime, new_file$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), pch = 46, lwd = 1, bty = "n")
plot(new_file$DateTime, new_file$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()